[workspace]
members = [
    "autostrata",
    "autostrata-macros",
    "autostrata-tui",
    "autostrata-web",
    "strata-uxr",
    "examples/web-components-demo",
    "examples/demo",
]
resolver = "2"
