[package]
name = "kano-basic-components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tui = ["kano/tui", "kano-tui"]
web = ["kano/web", "kano-web"]

[dependencies]
kano = { path = "../kano" }
kano-tui = { path = "../kano-tui", optional = true }
kano-web = { path = "../kano-web", optional = true }
