[package]
name = "demo"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
tui = ["autostrata-tui", "strata-uxr/tui"]
web = ["autostrata-web", "strata-uxr/web"]

[dependencies]
autostrata.path = "../../autostrata"
autostrata-tui = { path = "../../autostrata-tui", optional = true }
autostrata-web = { path = "../../autostrata-web", optional = true }
strata-uxr = { path = "../../strata-uxr" }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
js-sys = "0.3"
