[package]
name = "kano-macros"
version.workspace = true
license = "MIT"
authors = ["Audun Halland <audun.halland@pm.me>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
