[package]
name = "kano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tui = []
web = ["wasm-bindgen", "wasm-bindgen-futures"]

[dependencies]
kano-macros.path = "../kano-macros"
anyhow = "1"
lazy_static = "1"
futures = "0.3"
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
